language: csharp
solution: Task1CS.sln
branches:
  only:
    - task1-cs

mono: latest
install:
  - sudo apt-get install nuget
  - nuget restore Task1CS.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  
script:
  - xbuild /p:Configuration=Release Task1CS.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Task1CS.Test/bin/Release/Task1CS.Test.dll
