language: csharp
branches:
  except:
    - docs
env:
  global:
    - GH_REPO_NAME: PofCIS_Team1
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/lnupmi11/PofCIS_Team1.git
addons:
  apt:
    packages:
      - doxygen
      - graphviz
script:
- ./generate_docs.sh
